[View in Colaboratory](https://colab.research.google.com/github/findingfoot/ML_practice-codes/blob/master/Multiple_layers.ipynb)

In [0]:
import os
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tensorflow.python.framework import ops
ops.reset_default_graph()
import warnings
warnings.filterwarnings('ignore')

sess= tf.Session()

In [0]:
#creating an image of size 4x4

x_shape = [1,4,4,1]
x_val = np.random.uniform(size = x_shape)

In [0]:
x_data = tf.placeholder(tf.float32, shape = x_shape)

In [0]:
#Sliding convolution window. Stride 2 and size [2x2]

my_filter = tf.constant(0.25, shape = [2,2,1,1])
my_strides = [1,2,2,1]

mov_win = tf.nn.conv2d(x_data, my_filter, my_strides, padding = 'SAME', name = "Conv_Window")

In [0]:
# Define a custom layer which will be sigmoid(Ax+b) where
# x is a 2x2 matrix and A and b are 2x2 matrices
def custom_layer(input_matrix):
    input_matrix_sqeezed = tf.squeeze(input_matrix)
    A = tf.constant([[1., 2.], [-1., 3.]])
    b = tf.constant(1., shape=[2, 2])
    temp1 = tf.matmul(A, input_matrix_sqeezed)
    temp = tf.add(temp1, b) # Ax + b
    return(tf.sigmoid(temp))
  
with tf.name_scope('Custom_Layer') as scope:
    custom_layer1 = custom_layer(mov_win)

In [33]:
print(sess.run(mov_win, feed_dict = {x_data:x_val}))

[[[[0.40685707]
   [0.75601745]]

  [[0.45605925]
   [0.3971504 ]]]]


In [34]:
print(sess.run(custom_layer1, feed_dict={x_data: x_val}))

[[0.9104364 0.9275949]
 [0.8766758 0.8077466]]
