[View in Colaboratory](https://colab.research.google.com/github/pk1412/ML_practice-codes/blob/master/Tensorflow_placeholders.ipynb)

In [0]:
import numpy as np
import tensorflow as tf

#resetting the graph
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [0]:
sess = tf.Session()

In [0]:
var = tf.placeholder(tf.float32, shape = (4,4)) #shape can be list or tuple


In [38]:
#let us create an input data and operation to visualize on tensorboard. feed_dict to feed in the value of x into the graph
#keep the shape same as placeholder

input_data = np.random.random((4,4))


#operation same as input

op = tf.identity(var)

print(sess.run(op, feed_dict = {var: input_data}))

[[0.2683731  0.6823191  0.9123826  0.03228896]
 [0.8759085  0.46514112 0.93744    0.08851378]
 [0.9647845  0.04810917 0.09625556 0.13192602]
 [0.64295596 0.9150679  0.16171238 0.57204175]]


In [0]:

merged = tf.summary.merge_all()
writer = tf.summary.FileWriter('/tmp/variable_logs', sess.graph)