[View in Colaboratory](https://colab.research.google.com/github/pk1412/ML_practice-codes/blob/master/Tf_tensors.ipynb)

In [0]:
'''
loading the tensorflow and resetting the tesorflow graph

'''
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [0]:
''' Starting a graph session or the instance of tensorflow'''

sess = tf.Session()

In [0]:
#Initialize any tensor
var_tensor = tf.zeros((5,3))


#evaluating tensor with run method.
sess.run(var_tensor)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [0]:
#Creating a variable 

my_var = tf.Variable(var_tensor)


# Can't run the session without initializing the variable

sess.run(my_var.initializer)
sess.run(my_var)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [0]:
#Using row and column dim to initialize the tensor

row = 4
col = 3

zero_var = tf.Variable(tf.zeros([row,col]))
one_var = tf.Variable(tf.ones([row,col]))

sess.run(zero_var.initializer)
sess.run(one_var.initializer)
print(sess.run(zero_var))
print(sess.run(one_var))

In [0]:
x = tf.random_normal(shape=[5,3])
sess.run(x)

array([[ 0.49772677, -0.3120493 ,  1.0765785 ],
       [ 0.08036355, -0.7488156 ,  0.13051528],
       [ 0.53373986,  0.06046211, -1.3452994 ],
       [ 0.98806655,  2.0260167 ,  0.7473453 ],
       [ 0.2670394 ,  0.39922017, -2.693671  ]], dtype=float32)

In [0]:

'''
Filling variable with a constant
'''

fill_var = tf.Variable(tf.fill([row,col],-3))
sess.run(fill_var.initializer)

print(sess.run(fill_var))

[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]


In [0]:
fill_const_var = tf.Variable(tf.constant([5,2,6,3,76,7,1,4,6,2,6,7,2,5,7,]))
fill_const_var = tf.Variable(tf.constant([3,5,3,3,2,5,6,23,6,23,6,12], shape = [row,col]))

sess.run(fill_const_var.initializer)
print(sess.run(fill_const_var))

[[ 3  5  3]
 [ 3  2  5]
 [ 6 23  6]
 [23  6 12]]


In [0]:
'''
creating tensor from sequence generation function

'''

linear_var = tf.Variable(tf.linspace(1.,2.,15))

sess.run(linear_var.initializer)

sess.run(linear_var)



#range in tensorflow

range_var = tf.Variable(tf.range(1,21,3))
sess.run(range_var.initializer)
sess.run(range_var)

array([ 1,  4,  7, 10, 13, 16, 19])

In [0]:
rnom_var = tf.random_normal([row,col])

sess.run(rnom_var)

array([[ 2.7632418 , -0.1216739 , -1.2532767 ],
       [ 0.4536211 ,  0.87878615, -0.26912996],
       [-0.6570371 , -0.6466841 ,  0.6818237 ],
       [-0.56409496,  1.1443977 , -0.7503979 ]], dtype=float32)

In [0]:
#reset the graph

ops.reset_default_graph()


#start the graph session

sess = tf.Session()

#create variable

temp_var = tf.Variable(tf.lin_space(2.,6.,3))


#adding summaries to tensorboard

merged = tf.summary.merge_all()

# intialize the graph writer

writer = tf.summary.FileWriter('/tmp/variable_logs', graph = sess.graph)

# intialize the operation

initializer_op = tf.global_variables_initializer()

#run initialization of variable

sess.run(initializer_op)



'''
Run command :   tensorboard --logdir=/tmp

URL: http://localhost:6006

'''

'\nRun command :   tensorboard --logdir=/tmp\n\nURL: http://localhost:6006\n\n'