[View in Colaboratory](https://colab.research.google.com/github/findingfoot/ML_practice-codes/blob/master/Working_with_Matrices.ipynb)

In [0]:
import tensorflow as tf
import numpy as np

from tensorflow.python.framework import ops
ops.reset_default_graph()

In [0]:
sess = tf.Session()

In [4]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
A = tf.truncated_normal([2,3])

print(sess.run(A))

[[ 0.02334532  0.46713004 -0.41599032]
 [ 0.59580874 -0.14107002 -0.33487496]]


In [6]:
B = tf.fill([2,3],1.0)
print(sess.run(B))

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.740711   0.8397039 ]
 [0.8811586  0.6031524 ]
 [0.3789791  0.02844024]]


In [8]:
D = tf.convert_to_tensor(np.array([[1,2,3] , [4,6,2], [4,7,3]]), dtype=float)

print(sess.run(D))

[[1. 2. 3.]
 [4. 6. 2.]
 [4. 7. 3.]]


In [9]:
print(sess.run(A+B)*2.0)

[[2.3704622  2.099173   0.7565907 ]
 [0.7792487  4.230262   0.46542978]]


In [10]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(sess.run(tf.transpose(A)))

[[-1.9856371  -1.2714075 ]
 [-0.7859276   0.86523324]
 [-0.9627791  -0.39131317]]


In [12]:
print(sess.run(tf.matrix_determinant(D)))

8.0


In [13]:
print(sess.run(tf.matrix_inverse(D)))

[[ 0.5    1.875 -1.75 ]
 [-0.5   -1.125  1.25 ]
 [ 0.5    0.125 -0.25 ]]


In [14]:
#Cholesky decomposition
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#Eigenvectors and eigenvectors
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)

[-2.8689706 -1.2128597 14.081838 ]


In [16]:
print(eigenvectors)

[[ 0.3297113  -0.85722697  0.39554095]
 [ 0.48878777  0.5134439   0.70531005]
 [-0.8076985  -0.03921305  0.5882903 ]]
